### ISSUE TITLE
Clean up .travis.yml

### ISSUE THREAD

**Issue by monkbroc** [AKERKits/docs#2]
Hi! It's great that you're using the Particle docs tooling for your project. Isn't open source great?

Could you please remove the Slack integration from https://github.com/AKERKits/docs/blob/master/.travis.yml#L26 because we're seeing your Travis build status in the Particle Slack channel :)

**Comment by Amakaruk** [comment]
Done - thank you

**Comment by monkbroc** [comment]
Thanks!
